### ISSUE TITLE
Add validation for MavenCentral repositories

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper-maven-plugin#18]

**Comment by AnastasiiaSergienko** [comment]
Plugins: "nexus-staging-maven-plugin", "maven-source-plugin", "maven-gpg-plugin", "maven-javadoc-plugin", "maven-deploy-plugin".
I've also added a template with them to the release robot: https://github.com/exasol/release-robot/blob/feature/50_add_validations_for_maven_release/doc/user_guide/maven_central_release_pom_file_template.md

**Comment by jakobbraun** [comment]
still missing:

- [ ] maven-source-plugin
- [ ] maven-javadoc-plugin

**Comment by jakobbraun** [comment]
Closed by #65
