### ISSUE TITLE
Use same consistency check as release-droid

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper-maven-plugin#185]
Release-droid validation failed for project `elasticsearch-virtual-schema` with the following messages:

```
E-RD-REP-19: The file '.github/workflows/release_droid_release_on_maven_central.yml' does not exist in the project. Please, add this file. [For platforms: MAVEN]
E-RD-REP-20: Project description is missing in the pom.xml file. [For platforms: MAVEN]
E-RD-REP-20: Project URL is missing in the pom.xml file. [For platforms: MAVEN]
```

Project-keeper should use the same validation.

**Comment by jakobbraun** [comment]
If you want to release on maven, you need to add the `maven_central` module: https://github.com/exasol/project-keeper-maven-plugin#maven_central.

In that case I guess it's not added since we don't release the virtual schemas on maven.
