### ISSUE TITLE
Test report fails for Java build-next-java when there are no unit tests

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper-maven-plugin#210]
For projects that have no unit tests the test report of the build-next-java action fails.
```
Run scacap/action-surefire-report@v1
Going to parse results form **/surefire-reports/TEST-*.xml
 **/failsafe-reports/TEST-*.xml
Result: No test results found!
Posting status 'completed' with conclusion 'failure' to refs/heads/dependency-updates (sha: 9b0c4fae12b27675d1b59a549bfb7b4e23b9159a)
```

**Comment by pj-spoelders** [comment]
https://github.com/ScaCap/action-surefire-report/blob/master/README.md
there's an action input: 
`fail_if_no_tests`

> Optional. Check will fail if no tests were found. The default is true.
