### ISSUE TITLE
Validate .gitignore

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper-maven-plugin#51]
Force some lines to be present in **all** .gitignore files.

Each project can however still define it's own ignores.

Required lines:
```
connectToExasol.sh
.DS_Store
*.swp
local
Scripts
.dbeaver*
**/*.log
.directory
venv/
.idea
*.iml
target
.cache
dependency-reduced-pom.xml
.project
.classpath
pom.xml.versionsBackup
```

**Comment by redcatbear** [comment]
```
~*
*.lock
*.bak
*.orig
*.old
*.md.html
```

**Comment by AnastasiiaSergienko** [comment]
I wouldn't add `connectToExasol.sh` as a required file because some of our projects have nothing to do with the database.

**Comment by jakobbraun** [comment]
Ok so I will only require `connectToExasol.sh` if exasol-testconatiners are a dependency
